volumes:
  liquibase_mysql_data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-liquibase
    ports:
      - 3306:3306
    volumes:
      - liquibase_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: liquibase
      MYSQL_USER: liquibase
      MYSQL_PASSWORD: password
