spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/test?createDatabaseIfNotExist=true
#    username: liquibase
#    password: password
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.yaml
